### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by silverbag** [silverbag/furima_28698#10]
URL
・https://furima-28698.herokuapp.com/
出品者
・example@hoge.com
・a1a1a1
購入者
・abcde@gmail.com
・a1a1a1
テストカード情報
・4242424242424242
・23/3
・123

**Comment by kaho0919** [comment]
最終課題提出ありがとうございます。

出品挙動確認中にエラーが出てしまったため、確認をお願いします。
画像を０枚で出品したらエラーが出るかを確認した際、スラックにて画像で送りますエラーが出ました。

また、Basic認証が実装されていませんでしたので、そちらも確認お願いします。
出品数が1点でしたので、画面表示しただけで、購入済みの商品はどう出るかもわかるように何点か出品し、購入済みの物も用意しておいた方が見えやすいかなと思います。

以上３点確認し、修正後、再度フォームにて提出をお願いします。

**Comment by silverbag** [comment]
訂正いたしました。
basic認証のパスは
ユーザー名 admin
パスワード admin

**Comment by Toshi0917** [comment]
古田さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**

**Comment by Toshi0917** [comment]
最終課題提出ありがとうございます。
確認をお願いたします。

・用意している購入者用のアカウントでログインが出来ません
・決済時に住所を未入力で購入ボタンを押すとエラー画面に移行する

修正後、再度提出をお願い致します。

**Comment by silverbag** [comment]
ご確認頂きありがとうございます。
住所とは都道府県や番地など全ての値でしょうか？
それとも何か特定の値でしょうか？
よろしくお願い致します。

**Comment by silverbag** [comment]
購入者アカウント
aaaaaaaaaa@gmail.com
パスワード
a1a1a1
訂正いたしました。

**Comment by MasaakiTanabashi** [comment]
古田さん、ご提出ありがとうございます！
上記の修正確認しました。問題ありません。

それとは別に1点確認させてください。

◎出品者が商品の詳細ページを確認すると、見本のような「情報」が表示されません。
これは意図した表示でしょうか。
もし違うのであれば、修正をお願いいたします。

[Furima 見本](https://gyazo.com/7140e2183092628b1f54401ccaad91eb)

[古田さんのFurima](https://gyazo.com/b4e301d09a9ef8a289f4cd504e96c92d)


確認し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by silverbag** [comment]
詳細ページ訂正いたしました。
https://gyazo.com/72858ed53785198b716be0f8c88bc12d

**Comment by MasaakiTanabashi** [comment]
古田さん、再提出ありがとうございます！

◎アカウントによって、詳細ページの見え方が異なります。

- 出品者アカウント（example@hoge.com）では、「花」という商品の詳細ページが表示されません。それ以外は表示される。

- 購入者アカウント（aaaaaaaaaa@gmail.com）では、「花」の詳細ページは表示される。それ以外は表示されない。

確認お願いします。

**Comment by silverbag** [comment]
用件を勘違いしておりました。
訂正いたしました！！
よろしくお願い致します。

**Comment by MasaakiTanabashi** [comment]
古田さん、修正ありがとうございます！
挙動確認させて頂きましたが、問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
